FROM node:18

WORKDIR /app

COPY package.json ./
RUN npm install
COPY ./ ./
RUN npm run build

FROM nginx:alpine
COPY --from=0 /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/

EXPOSE 6969
CMD ["nginx", "-g", "daemon off;"]
